### ISSUE TITLE
Thumbnail Minimum Size wird nicht angewendet

### ISSUE THREAD

**Issue by BlackHawk3000** [g0nzo83/EVE-X-Preview#1]
Die minimum Thumbnail Größe wird nicht übernommen, die Thumbnails behalten die größe von der Standardeinstellung. 
In der JSON wird die Größe übernommen, ein Neustart der Anwendung und von EvE bringt keinen Erfolg. 

![grafik](https://github.com/g0nzo83/EVE-X-Preview/assets/70750116/96f91e94-36d4-49e2-a018-7a70d3304d43)

**Comment by g0nzo83** [comment]
Die Thumbnail minimum size bestimmt die Größe welche ein Thumbnail beim verkleinern nicht unterschreiten kann. das soll verhindern das man ausversehen das Thumbnail zu klein macht und es nicht mehr möglich ist es zu vergrößern. 
Default Thumbnail Location setzt das Thumbnail auf die auf die angegebene Größe wenn es erstellt wird. Dies ist unabhängig von Thumbnail minimum size.

**Comment by BlackHawk3000** [comment]
Check, deine Notes nochmal gelesen und die Tastenkombi gefunden um die Größe anzupassen.
