### ISSUE TITLE
previews lack the ability to interact like a normal window.

### ISSUE THREAD

**Issue by tylort69** [g0nzo83/EVE-X-Preview#2]
I like being able to set hotkeys from the gui and the amount of customization for previews is nice but I'm unable to interact with and size the previews as I would a normal window. with eve o preview I use http://windowgrid.net/ because the previews being unaligned is quite frustrating.

**Comment by g0nzo83** [comment]
To adjust the size and width, you need to use Mouse Gestures. The gestures are the same as in EVE-O with a few additional ones.
https://github.com/g0nzo83/EVE-X-Preview?tab=readme-ov-file#mouse-gestures-and-actions

When Window Snap is activated, the thumbnails should align perfectly with each other. This works much better in EVE-X than it does in EVE-O.
WindowGrind is unlikely to function properly as it partly uses the same Mouse Gestures as EVE-X.

**Comment by tylort69** [comment]
With window grid I can take any window [LMB] Hold on window border Hold [SPACE] and then Drag the mouse to position or resize the window. The Issue with EVE X Preview in this scenario is that there is no window border to Drag.

https://gyazo.com/050b5454a4dadee5b4fdff5c9fa89248

**Comment by tylort69** [comment]
for me with the current implementation it seems quite difficult and finicky to get say 6 previews perfectly sized spaced and aligned in a 3 wide 2 high grid without any wasted pixels on the monitor so that the 6 previews share an equal share of 100% width and height of the monitor.
Here is an example of my use case: https://i.imgur.com/IyMOj1R.jpeg
in any way that you think you can make this functionality possible I'm not opposed to, there is no requirement for it to be achieved with the use of window grid.

**Comment by g0nzo83** [comment]
You are aiming to ensure that the thumbnails perfectly fit your monitor space? 
So you only have to adjust the size of the thumbnails?
If you want all thumbnails to have the same size as shown in your image, I suggest using the "Thumbnail Minimum Size" option and then reduce the size of the thumbnails manually once with the mouse. Afterward, all thumbnails should have the exact size specified in the option, allowing you to arrange them on your screen similarly to what you have in EVE-O. you just have to make sure that you enter the correct size. Would this be a viable alternative solution for you?

Alternatively, you could consider arranging the thumbnails using an external script if you possess the coding skills required. 
Even if I were to add an option to display the titlebar of the thumbnails, it wouldn't be a quick fix. I prefer to wait until there are several suggestions that I can implement before releasing a new update.

**Comment by g0nzo83** [comment]
Like this?
![image](https://github.com/g0nzo83/EVE-X-Preview/assets/83645983/037cbd35-5e62-42cc-9117-784b7645da7b)

**Comment by tylort69** [comment]
yes that looks perfect, can that be replicated on 2 separate monitors at the same time?

**Comment by g0nzo83** [comment]
yes sure. but only if the size of the thumbnails is the same on both monitors. 
So i have a resolution of 2560x1440. divide it by 3 and round it to a integer that is width: 853
then 1440 - Taskbarsize(45px for me) / 3 = hight: 465
![image](https://github.com/g0nzo83/EVE-X-Preview/assets/83645983/bede3819-d2fc-464a-af30-4f1548b2995e)

I manually align the first one on the top left corner and then snap all the other on it so its perfect aligned. Do not forget to save the Thumbnail positions on the Task Icon, otherwise you'll have to do it again. 

If you have a different issue, please open a new one thread

**Comment by tylort69** [comment]
I guess the only extra functionality regarding this issue would be to allow manually setting x,y pos of specific previews so that I could set one manually exactly with coordinates (4480,1080) and then use the snapping feature to align the rest for that monitor and then again on another monitor I could manually set another preview to (3840,2260) and then again use the snapping to align the rest of the previews for the monitor.

**Comment by g0nzo83** [comment]
I will think about how and whether to implement this.
If you really want to set exact positions manually, you can still do it via the Json file for now

**Comment by g0nzo83** [comment]
This is not planned in the near future. 
Adding a title bar would require some major changes to the creation of thumbnails. 
Rendering the font and borders in this case requires different methods of handling events and redrawing. 
Adding a Setting to allow to set the position of thumbnails manually is very user specific.
it is doable by changing the values inside the json file for now or third party tools which can set window positions. 
This can be added if there is greater demand for it.
