### ISSUE TITLE
Inactive client borders

### ISSUE THREAD

**Issue by tylort69** [g0nzo83/EVE-X-Preview#4]
I think adding the option for a toggle for inactive clients to have a border that is different from the active client border and having it customizable the same as the active one is would be a nice to have feature.
![image](https://github.com/g0nzo83/EVE-X-Preview/assets/28652424/0a3bad60-04ea-428c-aa90-6dcbfa9c4eb1)

**Comment by g0nzo83** [comment]
Yes, this sounds good. there was an option to display all borders but i must have forgotten to implement this again into the GUI after switching from alpha to stable version. 
So you want a separate bordercolor for each client as it has already been implemented. only that the borders are always displayed and you want the bordercolor to change again when the client becomes active. 
Is that correct so far?

**Comment by tylort69** [comment]
By inactive I mean the client that does not currently have focus.
Allow the border of inactive clients to be customized like the active client border currently is so that I can have the inactive border at 2px but the active at say 5px.

(Active client 1){Border Green}
(Inactive client 2){Border Gray}
(Inactive client 3){Border Gray}
(Inactive client 4){Border Gray}

(Inactive client 1){Border Gray}
(Inactive client 2){Border Gray}
(Active client 3){Border Green}
(Inactive client 4){Border Gray}

**Comment by g0nzo83** [comment]
I have added it to the todo list

**Comment by g0nzo83** [comment]
Im not sure if the Show All Borders Checkbox should be in Thumbnail Settings or in Custom Colors section. It would fit in both areas, but I think it has more meaning in the Custom Colors
Settings would look like this:
![image](https://github.com/g0nzo83/EVE-X-Preview/assets/83645983/c098c672-1aee-4571-ac97-cda8f6dbb99c)

**Comment by tylort69** [comment]
This was more what I was thinking
![306680200-0a3bad60-04ea-428c-aa90-6dcbfa9c4eb1 (1)](https://github.com/g0nzo83/EVE-X-Preview/assets/28652424/9b0fb503-fd30-4746-91dc-eacf1986184d)
